### ISSUE TITLE
Cannot find module bignum.node

### ISSUE THREAD

**Issue by exceeded** [bonesoul/hypeserv#10]
Followed instructions to install this, and presented with the error: 

2017-12-08T11:18:53.302Z - error: startup error: Error: Cannot find module '/<omitted>/hypepool/node_modules/bignum/binding/bignum.node'

Can't seem to find it in the repo.

Thanks!

**Comment by exceeded** [comment]
Closing issue, instructions stated need to clone hypeengine.git, after which working.

Still have an issue with webserver not starting, but getting there.

**Comment by bonesoul** [comment]
The code is no where complete yet :) So don't expect a working pool as it still lacks implementation of stuff.
